spring:
  application:
    name: SpringSecurity
  datasource:
    url: jdbc:mysql://localhost:3306/security-demo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
